name: LoaderLib
description: A general purpose file loading and handling library.
version: 2.12.0
homepage: https://github.com/FarragoFiction/LoaderLib
author: paradoxLands
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: any
  csv: ^5.0.0-nullsafety.0
  CommonLib:
    git: https://github.com/FarragoFiction/CommonLib.git

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  test: any
